default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: test1234
  host: localhost

development:
  <<: *default
  database: book_api_development

test:
  <<: *default
  database: book_api_test

production:
  <<: *default
  database: book_api_production
